# Enable or disable elements.
# There are only listed ones, that may affect performance.
# true - enable
# false - disable

elements:
  # Checks on any player movement if player jumped using many checks.
  jump-event: true
  # Checks on any player movement if player is on new chunk
  chunk-enter-event: true